# Set to author to set pr creator as assignee
addAssignees: author

# A list of keywords to be skipped the process that add reviewers if pull requests (title) include it 
skipKeywords:
  - Automated Latest Dependency Updates
