on:
  workflow_dispatch:
    inputs:
      pypi_version:
        description: 'released PyPI version to use (ex - v1.11.1)'
        required: true

name: Create Feedstock PR
jobs:
  create_feedstock_pr:
    name: Create Feedstock PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout inputted version
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.inputs.pypi_version }}
          path: "./woodwork"
      - name: Pull latest from upstream for user forked feedstock
        run: |
          gh auth status
          gh repo sync alteryx/woodwork-feedstock --branch main --source conda-forge/woodwork-feedstock --force
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: alteryx/woodwork-feedstock
          ref: main
          path: "./woodwork-feedstock"
          fetch-depth: '0'
      - name: Run Create Feedstock meta YAML
        id: create-feedstock-meta
        uses: alteryx/create-feedstock-meta-yaml@v3
        with:
          project: "woodwork"
          pypi_version: ${{ github.event.inputs.pypi_version }}
          setup_cfg_filepath: "woodwork/setup.cfg"
          meta_yaml_filepath: "woodwork-feedstock/recipe/meta.yaml"
      - name: View updated meta yaml
        run: cat woodwork-feedstock/recipe/meta.yaml
      - name: Push updated yaml
        run: |
          cd woodwork-feedstock
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.email "machineOSS@alteryx.com"
          git config --global user.name "machineAYX Bot"
          git remote set-url origin https://${{ secrets.AUTO_APPROVE_TOKEN }}@github.com/alteryx/woodwork-feedstock
          git checkout -b ${{ github.event.inputs.pypi_version }}
          git add recipe/meta.yaml
          git commit -m "auto commit"
          git push origin ${{ github.event.inputs.pypi_version }}
      - name: Adding URL to job output
        run: |
          echo "Conda Feedstock Pull Request: https://github.com/alteryx/woodwork-feedstock/pull/new/${{ github.event.inputs.pypi_version }}" >> $GITHUB_STEP_SUMMARY
