on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Install Test
jobs:
  install_ww_complete:
    name: ${{ matrix.python_version }} install woodwork complete
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build woodwork package
        run: make package_woodwork
      - name: Install complete version of woodwork
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install "$(cat dev-requirements.txt | grep codecov)"
          python -m pip install -r unpacked_sdist/test-requirements.txt
          python -m pip install -e unpacked_sdist/[complete]
      - name: Test by importing packages
        run: |
          printf "import alteryx_open_src_update_checker \nimport woodwork" >> 'test_update_checker.py'
          coverage erase
          pytest test_update_checker.py --cov=woodwork --cov-config=./.coveragerc
        env:
          ALTERYX_OPEN_SRC_UPDATE_CHECKER: False
      - if: ${{ matrix.python_version == 3.7 }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
