name: Kickoff Featuretools & EvalML Unit Tests

# on:
  # push:
  #   branches:
  #     - main
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kickoff:
    name: Run FT and EvalML unit tests
    if: github.repository_owner == 'alteryx'
    runs-on: ubuntu-latest
    steps:
      - name: Run workflow for Featuretools unit tests
        # run: gh workflow run unit_tests_with_woodwork_main_branch.yaml --repo "alteryx/featuretools"
        run: gh workflow run "Unit Tests - Featuretools with Woodwork main branch" --repo "alteryx/featuretools"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Run workflow for EvalML unit tests
        run: gh workflow run unit_tests_with_woodwork_main_branch.yaml --repo "alteryx/evalml"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
