name: Unit Tests - Minimum Dependencies
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  py36_unit_tests_minimum_dependencies:
    name: 3.6 unit tests minimum dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        optional_libraries: ["core", "optional"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install woodwork - minimum tests requirements
        run: |
          python -m pip install -r woodwork/tests/minimum_test_requirements.txt
      - if: ${{ matrix.optional_libraries == 'optional' }}
        name: Install woodwork - minimum dask, koalas, core requirements
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jre-headless
          JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          python -m pip install -r minimum_core_optional_requirements.txt
      - if: ${{ matrix.optional_libraries == 'core' }}
        name: Install woodwork - minimum core requirements
        run: |
          python -m pip install -r woodwork/tests/minimum_core_requirements.txt
      - name: Run unit tests without code coverage
        run: |
          python -m pytest woodwork/ -n 2