name: Pull Request Check
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  pull_request_check:
    name: pull request check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'main'
          repository: 'nearform/github-action-check-linked-issues'
          path: 'github-action-check-linked-issues'
      - name: Print helpful error message
        run: ls
      - uses: ./github-action-check-linked-issues
        id: check-linked-issues
        with:
          exclude-branches: "release_v/**, backport_v/**, main, latest-dep-update-/**, min-dep-update-/**, dependabot/**"
          comment: false
      - name: Print helpful error message
        if: always()
        run: |
          msg="Linked issues: ${{ steps.check-linked-issues.outputs.linked_issues_count }}"
          echo $msg 
          echo $msg >> $GITHUB_STEP_SUMMARY
          msg="If count is 0, please link the pull request to the issue(s) it resolves."
          echo $msg 
          echo $msg >> $GITHUB_STEP_SUMMARY
          msg="If you are not sure how to do this, please see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue"
          echo $msg
          echo $msg >> $GITHUB_STEP_SUMMARY