on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

name: Unit Tests - Latest Dependencies
jobs:
  unit_latest_tests:
    name: ${{ matrix.python_version }} unit tests ${{ matrix.libraries }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - python_version: "3.8"
            core_dependencies: false
            command: 'git-test-automl'
        python_version: ["3.7", "3.8", "3.9", "3.10"]
        libraries: ["core", "dask", "spark"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build woodwork package
        run: make package_woodwork
      - name: Set up pip
        run: |
          pip config --site set global.progress_bar off
      - name: Install woodwork - requirements
        run: |
          python -m pip install -e unpacked_sdist/
      - name: Install woodwork - tests requirements
        run: |
          python -m pip install unpacked_sdist/[test]
      - if: ${{ matrix.libraries == 'spark' }}
        name: Install woodwork - spark requirements
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jre-headless
          JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          python -m pip install unpacked_sdist/[spark]
      - if: ${{ matrix.libraries == 'dask' }}
        name: Install woodwork - dask requirements
        run: |
          python -m pip install unpacked_sdist/[dask]
      - if: ${{ matrix.python_version != 3.8 }}
        name: Run unit tests (no code coverage)
        run: |
          cd unpacked_sdist
          pytest woodwork/ -n 2
        env:
          PYARROW_IGNORE_TIMEZONE: 1
          ALTERYX_OPEN_SRC_UPDATE_CHECKER: False
      - if: ${{ matrix.python_version == 3.8 }}
        name: Run unit tests with code coverage
        run: |
          python -m pip install "$(cat setup.cfg | grep codecov)"
          coverage erase
          cd unpacked_sdist/
          coverage erase
          pytest woodwork/ -n 2 --cov=woodwork --cov-config=../.coveragerc
        env:
          PYARROW_IGNORE_TIMEZONE: 1
          ALTERYX_OPEN_SRC_UPDATE_CHECKER: False
      - if: ${{ matrix.python_version == 3.8 }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
