on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Unit Tests - Latest Dependencies
jobs:
  unit_latest_tests:
    name: ${{ matrix.python_version }} unit tests ${{ matrix.libraries }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get number of CPU cores
        id: cpu_cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: run tests
        run: echo ${{ steps.cpu_cores.outputs.count }}
      - name: run tests
        run: printf ${{ steps.cpu_cores.outputs.count }}
