name: Run looking glass performance tests via Airflow

on:
  push:
    branches:
      - main
      - lg_airflow_merge_perf_tests

jobs:
  performance_tests:
    name: Run looking glass performance tests via airflow
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Generate ISO timestamp
        run: |
          echo "TIMESTAMP=$(date +"%Y-%m-%dT%H:%M:%S.%3NZ")" >> $GITHUB_ENV
      - name: Checkout woodwork
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get commit hashes
        id: get_hashes
        run: |
          echo "CURRENT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "Latest commit hash: ${{ env.CURRENT_HASH }}"
          echo "PREVIOUS_HASH=$(git rev-parse --short HEAD~1)" >> $GITHUB_ENV
          echo "Previous commit hash: ${{ env.PREVIOUS_HASH }}"
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Run airflow tests and generate report
        run: | 
          curl --location --request POST '${{ secrets.AIRFLOW_BASE_URL }}dags/woodwork_run_tests_generate_report/dagRuns' \
          -u '${{ secrets.AIRFLOW_WW_USER }}:${{ secrets.AIRFLOW_WW_PASS }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "conf": {
                  "description": null,
                  "lg_branch": "lg_baton_airflow",
                  "n_trials": 1,
                  "pytest_args": {},
                  "python_version": "3.8",
                  "scenario_count_limit": null,
                  "scenarios_yaml": "woodwork_scenarios.yaml",
                  "woodwork_branch_previous": "${{ env.PREVIOUS_HASH }}",
                  "woodwork_branch_new": "${{ env.CURRENT_HASH }}",
                  "username": "${{ secrets.AIRFLOW_WW_USER }}",
                  "author": "${{ github.event.head_commit.author.name }}"
                },
            "logical_date": "${{ env.TIMESTAMP }}",
            "dag_run_id": "api_woodwork_run_tests_generate_report_${{ env.TIMESTAMP }}"
          }'
